# Generated by Django 5.0.7 on 2024-12-03 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=255, unique=True)),
                ('nominal_capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('nominal_energy', models.IntegerField(blank=True, default=1, null=True)),
                ('nominal_cycles', models.IntegerField(blank=True, default=1, null=True)),
                ('gravimetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('volumetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('industry_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('nominal_voltage', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('operating_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ac_resistance', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('max_self_discharge_rate', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('nominal_SOC_at_delivery', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('cell_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('cell_charging_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('cell_discharging_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-30.0), django.core.validators.MaxValueValidator(60.0)])),
                ('cell_dimension', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('frequency', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amplitude', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phase', models.FloatField()),
                ('current_offset', models.FloatField()),
                ('v_start', models.FloatField()),
                ('v_end', models.FloatField()),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(5600.0)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis', to='batteries.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('battery_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('original_power_capability', models.IntegerField(blank=True, default=0, null=True)),
                ('expected_EndOfLife', models.DateField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('manufactured_place', models.CharField(blank=True, max_length=2000, null=True)),
                ('battery_dimensions', models.CharField(blank=True, max_length=1000, null=True)),
                ('manufacturer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('sot', models.FloatField()),
                ('phase', models.FloatField()),
                ('soc', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='batteries.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_module_name', models.CharField(max_length=255)),
                ('battery_module_name', models.CharField(max_length=255)),
                ('battery_module_energy', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('battery_usable_energy', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('max_output_power', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('peak_output_power', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('nominal_voltage', models.IntegerField(blank=True, default=0, null=True)),
                ('operating_voltage_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('power_module_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('battery_module_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('operating_temperature', models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(60.0)])),
                ('max_operating_altitude', models.IntegerField(blank=True, default=1, null=True)),
                ('noise_emission', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3, null=True)),
                ('cell_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery_module_dimension', models.CharField(blank=True, max_length=1000, null=True)),
                ('power_module_dimension', models.CharField(blank=True, max_length=1000, null=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batteries.battery')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='batteries.module'),
        ),
    ]
