# Generated by Django 5.0.7 on 2024-07-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batteries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=40)),
                ('weight', models.FloatField(blank=True, default=0.1, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('original_power_capability', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacture_date', models.DateField()),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
            },
        ),
    ]
