# Generated by Django 5.0.7 on 2024-12-03 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='operating_temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='operating_voltage_range',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
