# Generated by Django 5.0.7 on 2024-07-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batteries',
            old_name='battery',
            new_name='manufacturer',
        ),
    ]
