# Generated by Django 5.0.7 on 2025-02-03 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField()),
                ('zipcode', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazardus', models.BooleanField(default=False)),
                ('extinguising_agent', models.CharField(blank=True, choices=[('fe', 'fire extinguiser')], max_length=3, null=True)),
                ('chemical_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_material', models.BooleanField(default=False)),
                ('recycled_material', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_feature', models.CharField(choices=[('tm', 'thermal management'), ('op', 'overcharge protection'), ('sc', 'short-circuit prevention')], max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.address'),
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=255, unique=True)),
                ('nominal_capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('nominal_energy', models.IntegerField(blank=True, default=1, null=True)),
                ('nominal_cycles', models.IntegerField(blank=True, default=1, null=True)),
                ('gravimetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('volumetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('industry_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('nominal_voltage', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('operating_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ac_resistance', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('max_self_discharge_rate', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('nominal_SOC_at_delivery', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('cell_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('cell_charging_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('cell_discharging_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-30.0), django.core.validators.MaxValueValidator(60.0)])),
                ('cell_chemistry', models.ManyToManyField(blank=True, related_name='cells', to='batteries.chemical')),
                ('cell_dimension', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimension')),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='EIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('frequency', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amplitude', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phase', models.FloatField()),
                ('current_offset', models.FloatField()),
                ('v_start', models.FloatField()),
                ('v_end', models.FloatField()),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(5600.0)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis', to='batteries.cell')),
            ],
            options={
                'verbose_name_plural': 'EIS',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('battery_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('original_power_capability', models.IntegerField(blank=True, default=0, null=True)),
                ('expected_EndOfLife', models.DateField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('manufactured_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.address')),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer')),
                ('battery_dimensions', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimension')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='batteries.material')),
                ('safety_features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='batteries.safetyfeature')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('sot', models.FloatField()),
                ('phase', models.FloatField()),
                ('soc', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='batteries.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_module_name', models.CharField(max_length=255)),
                ('battery_module_name', models.CharField(max_length=255)),
                ('battery_module_energy', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('battery_usable_energy', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('max_output_power', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('peak_output_power', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True)),
                ('nominal_voltage', models.IntegerField(blank=True, default=0, null=True)),
                ('operating_voltage_range', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('power_module_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('battery_module_weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('operating_temperature', models.FloatField(blank=True, null=True)),
                ('max_operating_altitude', models.IntegerField(blank=True, default=1, null=True)),
                ('noise_emission', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3, null=True)),
                ('cell_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batteries.battery')),
                ('battery_module_dimension', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_module_dimension', to='batteries.dimension')),
                ('power_module_dimension', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_module_dimension', to='batteries.dimension')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='batteries.module'),
        ),
        migrations.DeleteModel(
            name='Batteries',
        ),
    ]
