# Generated by Django 5.0.7 on 2024-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='operating_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
