# Generated by Django 5.0.7 on 2024-09-03 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_rename_battery_batteries_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_module_name', models.CharField(max_length=40)),
                ('battery_module_name', models.CharField(max_length=40)),
                ('battery_module_energy', models.FloatField(blank=True, default=0.1, null=True)),
                ('battery_usable_energy', models.FloatField(blank=True, default=0.1, null=True)),
                ('max_output_power', models.FloatField(blank=True, default=0.1, null=True)),
                ('peak_output_power', models.FloatField(blank=True, default=0.1, null=True)),
                ('nominal_voltage', models.IntegerField(blank=True, default=0, null=True)),
                ('operating_voltage_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('communication', models.CharField(blank=True, max_length=40, null=True)),
                ('power_module_dimension', models.CharField(blank=True, max_length=40, null=True)),
                ('power_module_weight', models.FloatField(blank=True, default=1.0, null=True)),
                ('battery_module_dimension', models.CharField(blank=True, max_length=40, null=True)),
                ('battery_module_weight', models.FloatField(blank=True, default=1.0, null=True)),
                ('operating_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(60.0)])),
                ('max_operating_altitude', models.IntegerField(blank=True, default=1, null=True)),
                ('noise_emission', models.FloatField(blank=True, default=1.0, null=True)),
                ('cell_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batteries.batteries')),
            ],
        ),
    ]
