# Generated by Django 5.0.7 on 2024-09-03 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=40)),
                ('nominal_capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('nominal_energy', models.IntegerField(blank=True, default=1, null=True)),
                ('cell_chemistry', models.CharField(blank=True, max_length=40, null=True)),
                ('nominal_cycles', models.IntegerField(blank=True, default=1, null=True)),
                ('gravimetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('volumetric_energy_density', models.IntegerField(blank=True, default=1, null=True)),
                ('industry_standard', models.CharField(blank=True, max_length=40, null=True)),
                ('nominal_voltage', models.FloatField(blank=True, default=1.0, null=True)),
                ('operating_voltage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ac_resistance', models.FloatField(blank=True, default=0.1, null=True)),
                ('max_self_discharge_rate', models.FloatField(blank=True, default=1.0, null=True)),
                ('nominal_SOC_at_delivery', models.FloatField(blank=True, default=1.0, null=True)),
                ('cell_dimension', models.CharField(blank=True, max_length=40, null=True)),
                ('cell_weight', models.FloatField(blank=True, default=1.0, null=True)),
                ('cell_charging_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('cell_discharging_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-30.0), django.core.validators.MaxValueValidator(60.0)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='batteries.module')),
            ],
        ),
    ]
