# Generated by Django 5.0.7 on 2025-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_alter_chemical_chemical_name_alter_dimension_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='manufactured_place',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='module',
            name='battery_module_dimension',
        ),
        migrations.RemoveField(
            model_name='module',
            name='power_module_dimension',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='battery_dimensions',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_dimension',
        ),
        migrations.AddField(
            model_name='battery',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufactured_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufactured_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufactured_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufactured_zipcode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='street',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='zipcode',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='power_module_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='power_module_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='power_module_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
