# Generated by Django 5.0.7 on 2024-10-06 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField()),
                ('zipcode', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazardus', models.BooleanField(default=False)),
                ('chemical_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name_plural': 'Cells'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterField(
            model_name='cell',
            name='ac_resistance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_charging_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_chemistry',
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_discharging_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(-30.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='industry_standard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='max_self_discharge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='nominal_SOC_at_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='nominal_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='operating_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_energy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_usable_energy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='communication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='max_output_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='noise_emission',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='operating_temperature',
            field=models.DecimalField(decimal_places=3, max_digits=3, validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='peak_output_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.address'),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('battery_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('original_power_capability', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacture_date', models.DateField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer', unique=True)),
                ('battery_dimensions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimensions', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Batteries',
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batteries.battery'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimensions', unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_module_dimension', to='batteries.dimensions', unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_module_dimension', to='batteries.dimensions', unique=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='cell_chemistry',
            field=models.ManyToManyField(blank=True, null=True, related_name='cells', to='batteries.chemical'),
        ),
        migrations.DeleteModel(
            name='Batteries',
        ),
    ]
