# Generated by Django 5.0.7 on 2024-10-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0005_address_chemical_dimensions_alter_cell_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_material', models.BooleanField(default=False)),
                ('recycled_material', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_feature', models.CharField(choices=[('tm', 'thermal management'), ('op', 'overcharge protection'), ('sc', 'short-circuit prevention')], max_length=2, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='manufacture_date',
            new_name='manufactured_date',
        ),
        migrations.AddField(
            model_name='battery',
            name='expected_EndOfLife',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufactured_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.address'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='extinguising_agent',
            field=models.CharField(blank=True, choices=[('fe', 'fire extinguiser')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='batteries.materials'),
        ),
        migrations.AddField(
            model_name='battery',
            name='safety_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='batteries.safetyfeatures'),
        ),
    ]
