# Generated by Django 5.0.7 on 2025-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0005_remove_battery_manufactured_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='chemical_name',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='critical_material',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='recycled_material',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='safety_feature',
            field=models.CharField(choices=[('tm', 'thermal management'), ('op', 'overcharge protection'), ('sc', 'short-circuit prevention')], default=0, max_length=2),
        ),
    ]
