# Generated by Django 5.0.7 on 2025-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0006_alter_chemical_chemical_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
