# Generated by Django 5.0.7 on 2024-10-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0006_materials_safetyfeatures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_dimensions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimensions'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='manufacturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_dimension',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimensions'),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_dimension',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_module_dimension', to='batteries.dimensions'),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_dimension',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_module_dimension', to='batteries.dimensions'),
        ),
    ]
