# Generated by Django 5.0.7 on 2025-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0007_alter_manufacturer_number_alter_manufacturer_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='capacity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='original_power_capability',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
