# Generated by Django 5.0.7 on 2024-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0007_alter_battery_battery_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_chemistry',
            field=models.ManyToManyField(blank=True, related_name='cells', to='batteries.chemical'),
        ),
    ]
