# Generated by Django 5.0.7 on 2024-11-14 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0008_alter_cell_cell_chemistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellSlave',
            fields=[
                ('cell_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='battery',
            name='battery_dimensions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.dimensions'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='batteries.address'),
        ),
        migrations.CreateModel(
            name='EIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('frequency', models.FloatField()),
                ('amplitude', models.FloatField()),
                ('phase', models.FloatField()),
                ('current_offset', models.FloatField()),
                ('v_start', models.FloatField()),
                ('v_end', models.FloatField()),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(5600.0)])),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis', to='batteries.cellslave')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('sot', models.FloatField()),
                ('phase', models.FloatField()),
                ('soc', models.FloatField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='batteries.cellslave')),
            ],
        ),
    ]
