# Generated by Django 5.0.7 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0008_alter_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='expected_EndOfLife',
        ),
        migrations.AddField(
            model_name='battery',
            name='expected_endoflife',
            field=models.DateField(blank=True, null=True),
        ),
    ]
