# Generated by Django 5.0.7 on 2025-02-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0009_remove_battery_expected_endoflife_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
