# Generated by Django 5.0.7 on 2024-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0009_cellslave_alter_battery_battery_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eis',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-01-01 01:00:00'),
            preserve_default=False,
        ),
    ]
