# Generated by Django 5.0.7 on 2024-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0010_eis_taken_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eis',
            old_name='taken_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='taken_at',
            new_name='added_at',
        ),
    ]
