# Generated by Django 5.0.7 on 2025-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0010_alter_battery_height_alter_battery_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='manufactured_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='manufactured_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
