# Generated by Django 5.0.7 on 2024-11-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0011_rename_taken_at_eis_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eis',
            name='cell_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis', to='batteries.cell'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cell_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='batteries.cell'),
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={},
        ),
        migrations.RemoveField(
            model_name='cell',
            name='ac_resistance',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_charging_temperature',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_chemistry',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_dimension',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_discharging_temperature',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_name',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_weight',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='gravimetric_energy_density',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='industry_standard',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='max_self_discharge_rate',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='module',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='nominal_SOC_at_delivery',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='nominal_capacity',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='nominal_cycles',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='nominal_energy',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='nominal_voltage',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='operating_voltage',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='volumetric_energy_density',
        ),
        migrations.AddField(
            model_name='cell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-01-01 01:01:01'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CellSlave',
        ),
    ]
