# Generated by Django 5.0.7 on 2025-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0011_alter_battery_manufactured_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='battery_module_energy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_module_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='battery_usable_energy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='max_output_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='noise_emission',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='peak_output_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='power_module_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
