# Generated by Django 5.0.7 on 2025-02-11 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0012_alter_module_battery_module_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='ac_resistance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_charging_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_discharging_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, validators=[django.core.validators.MinValueValidator(-30.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='max_self_discharge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='nominal_SOC_at_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='nominal_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='operating_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
