# Generated by Django 5.0.7 on 2024-11-19 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0012_alter_eis_cell_id_alter_measurement_cell_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eis',
            name='amplitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eis',
            name='frequency',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
