# Generated by Django 5.0.7 on 2025-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0013_alter_cell_ac_resistance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='nominal_SOC_at_delivery',
        ),
        migrations.AddField(
            model_name='cell',
            name='nominal_soc_at_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=22, null=True),
        ),
    ]
