# Generated by Django 5.0.7 on 2025-02-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0014_remove_cell_nominal_soc_at_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='batteries.manufacturer'),
        ),
    ]
