# Generated by Django 5.0.7 on 2025-02-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0015_alter_battery_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='batteries.manufacturer'),
        ),
        migrations.AddField(
            model_name='module',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batteries.manufacturer'),
        ),
    ]
