name: battery2life

services:
  api:
    build: ./battery2life
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./battery2life:/usr/src/app
    env_file:
      - ./battery2life/.env.dev

volumes:
  api: