name: battery2life

services:
  api:
    build: ./battery2life
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8000:8000
    volumes:
      - ./battery2life:/usr/src/app
      - ./battery2life/app.log:/usr/src/app/app.log
    env_file:
      - ./battery2life/.env.dev
    networks:
      - db 


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    networks:
      - mosquitto


  mosquitto-client:
    build: ./mosquitto-client
    container_name: mosquitto-client
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_KEEPALIVE=60
      - MQTT_USER=user1
      - MQTT_PASSWORD=user1
    volumes:
      - ./mosquitto-client/mosquitto-client.log:/usr/src/mosquitto-client/mosquitto-client.log
    networks:
      - mosquitto
      - db
    command: [ "python3",  "mosquitto_client.py" ]


  db:
    image: postgres:17.0
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data:/usr/src/data
    env_file:
      - ./battery2life/.env.dev
    networks:
      - mosquitto
      - db 

    
volumes:
  api:
  mosquitto:

networks:
  mosquitto:
    name: mosquitto
    driver: bridge
  db :
    name: db 
    driver: bridge