services:
  api:
    build: ./battery2life
    container_name: api
    restart: unless-stopped
    command: >
      sh -c " python manage.py makemigrations --noinput &&
              python manage.py migrate &&
              python manage.py create_admin &&
              python manage.py runserver 0.0.0.0:8000 
      "
    depends_on: 
      - db
    ports:
      - 8000:8000
    volumes:
      - ./battery2life:/usr/src/app
      - ./battery2life/app.log:/usr/src/app/app.log
    env_file:
      - ./.env.dev
    networks:
      - db
    

  db:
    image: postgres:17.0
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/data
      - ./database/dummy_data:/data
      - ./database/populate_dummy.sql:/populate_dummy.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=b2l
    networks:
      - db


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    networks:
      - mosquitto


  mosquitto-client:
    build: ./mosquitto-client
    container_name: mosquitto-client
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_KEEPALIVE=60
      - MQTT_USER=user1
      - MQTT_PASSWORD=user1
    volumes:
      - ./mosquitto-client/mosquitto-client.log:/usr/src/mosquitto-client/mosquitto-client.log
    networks:
      - mosquitto
    command: [ "python3",  "mosquitto_client.py" ]

    
volumes:
  battery2life:
  pgdata: 
  mosquitto-client:
  mosquitto:

networks:
  mosquitto:
    driver: bridge
  db:
    driver: bridge