\copy batteries_chemical             from '/data/chemical.csv'          with (format csv, delimiter ',', header);
\copy batteries_material             from '/data/material.csv'          with (format csv, delimiter ',', header);
\copy batteries_safetyfeature        from '/data/safety_feature.csv'    with (format csv, delimiter ',', header);

\copy batteries_manufacturer (id, name, email, city, street, number, zipcode)        from '/data/manufacturer.csv'      with (format csv, delimiter ',', header);

\copy batteries_battery (id, serial_number, battery_name, weight, capacity, original_power_capability, expected_endoflife, manufactured_date, height, width, length, manufactured_city, manufactured_street, manufactured_number, manufactured_zipcode, material_id, safety_features_id, manufacturer_id)  from '/data/battery.csv'           with (format csv, delimiter ',', header);

\copy batteries_module (id,power_module_name,battery_module_name,battery_module_energy,battery_usable_energy,max_output_power,peak_output_power,nominal_voltage,operating_voltage_range,communication,power_module_weight,battery_module_weight,operating_temperature,max_operating_altitude,noise_emission,cell_technology,created_at,updated_at,height,width,length,power_module_height,power_module_width,power_module_length,battery_id) from '/data/module.csv' with (format csv, delimiter ',', header);

\copy batteries_cell (id,nominal_capacity,nominal_energy,nominal_cycles,gravimetric_energy_density,volumetric_energy_density,industry_standard,nominal_voltage,operating_voltage,ac_resistance,max_self_discharge_rate,nominal_soc_at_delivery,cell_weight,cell_name,cell_charging_temperature,cell_discharging_temperature,height,width,length,module_id) from '/data/cell.csv' with (format csv, delimiter ',', header);

-- this table is generated by the Cell model from attribute cell_chemistry as a table to enable join between Cell and Chemistry
\copy batteries_cell_cell_chemistry  from '/data/batteries_cell_cell_chemistry.csv'         with (format csv, delimiter ',', header);

\copy batteries_measurement          from '/data/measurement.csv'       with (format csv, delimiter ',', header);
\copy batteries_eis                  from '/data/eis.csv'               with (format csv, delimiter ',', header);
